on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'
    branches:
      - [main, beta]

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
        #[semantic-release]: node version >=20.8.1 is required. Found v18.20.5.
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run build
      - run: bun run test


      # - run: bunx standard-version
      # - run: git push --follow-tags origin main
      # - run: npm publish

      - run: bunx semantic-release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
